capstone/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("sport.urls")),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)  # Static returns a list of path, not a path itself.

sport/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
	path("studio", views.index_studio, name="index_studio"),
    path("login", views.login_view, name="login"),
    path("partner_login", views.login_view_partner, name="partner-login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("register_studio", views.register_studio, name="register_studio"),
    path("try", views.try_view, name="try"),
    path("plans", views.plans_view, name="plans"),
	path("plans-studio", views.plans_studio_view, name="plans-studio"),
    path("credits", views.credits_view, name="credits"),
	path("credits-studio", views.credits_studio_view, name="credits-studio"),
    path("aboutus", views.aboutus_view, name="aboutus"),
    path("careers", views.careers_view, name="careers"),
    path("press", views.press_view, name="press"),
    path("contactus", views.contactus_view, name="contactus"),
    path("helpcenter", views.helpcenter_view, name="helpcenter"),
    path("partner", views.partner_view, name="partner"),
	path("partner-studio", views.partner_studio_view, name="partner-studio"),
    path("referfriend", views.referfriend_view, name="referfriend"),
    path("locations", views.locations_view, name="locations"),
    path("sport/<str:title>", views.entry, name="entry"),
    path("profile", views.view_profile, name="profile"),
    path("edit_profile_data", views.edit_profile_data, name="edit_profile_data"),
	path("add_review", views.add_review, name="add_review"),
	path("save_review", views.save_review, name="save_review"),

    # API Routes
    path("show_classes_for_day", views.show_classes_for_day, name="show_classes_for_day"),
    path("show_all_classes", views.show_all_classes, name="show_all_classes"),
    path("show_chosen_class/<int:class_id>", views.show_chosen_class, name="show_chosen_class"),
	path("class_signup", views.sign_up_for_class, name="sign_up_for_class"),
	path("class_cancel", views.cancel_class, name="cancel_class"),
	path("signed_up_classes_list", views.get_signed_up_classes_list, name="signed_up_classes_list"),
	path("class_reviews/<int:class_id>", views.get_class_reviews, name="get_class_reviews"),
	path("change_plan", views.change_plan, name="change_plan"),
]

sport/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from multiselectfield import MultiSelectField
import datetime
import pytz
from geopy.geocoders import Nominatim
import json
from django import forms

# Create your models here.


class User(AbstractUser):
    available_cities = [
        ("WA", "Warszawa"),
        ("KR", "Kraków"),
        ("LO", "Łódź"),
        ("GD", "Gdańsk)"),
        ("WR", "Wrocław"),
        ("PO", "Poznań"),
	]

    available_plans = [
        ("9", "9 credits/mo"),
        ("25", "25 credits/mo"),
        ("47", "47 credits/mo"),
        ("64", "64 credits/mo"),
        ("80", "80 credits/mo"),
    ]

    id              = models.AutoField(primary_key=True)
    profile_photo   = models.ImageField(
        upload_to='user_profiles',
        height_field=None,
        width_field=None,
        default='user_profiles/MockupPhoto01.png'
        )
    city			= models.CharField(max_length=16, choices=available_cities, default="Warszawa")
    classes			= models.ManyToManyField('sport.Class', related_name='user_classes', blank=True)
    reviews			= models.ManyToManyField('sport.Review', related_name='user_reviews', blank=True)
    credits         = models.PositiveSmallIntegerField(default = 0)
    plan            = models.CharField(max_length=16, choices=available_plans, default="47 credits/mo")
    studio_owner    = models.BooleanField(default="False")

    def __str__(self):
        return f"User {self.id}: {self.last_name},{self.first_name}"

    def get_letter(self):
        #swaping first name with username, as user is not initially requested to fill all data
        if len(self.first_name) == 0:
            self.first_name = self.username
        name = self.first_name
        letter = name[0]
        return letter

    def get_plan_credits(self):
        credits = self.plan.strip(" credits/mo")
        return int(credits)

    def get_price(self):
        plan = self.plan.strip(" credits/mo")
        if plan == "9":
            price = 39
        elif plan == "25":
            price = 59
        elif plan == "47":
            price = 79
        elif plan == "64":
            price = 99
        elif plan == "80":
            price = 119
        return int(price)

    def serialize(self):
        return {
            "id"                : self.id,
            "username"          : self.username,
            "first_name"        : self.first_name,
            "last_name"         : self.last_name,
            "email"             : self.email,
            "profile_photo"     : self.profile_photo.url,
            "city"              : self.city,
            "classes"           : [this_class.id for this_class in self.classes.all()],
            "reviews"           : [review.id for review in self.reviews.all()],
            "credits"           : self.credits,
            "studio_owner"      : self.studio_owner,
        }

    def get_number_classes_taken(self):
        classes_all = []
        for i in self.classes.all():
            classes_all.append(i.time)
        classes_taken = []
        now = datetime.datetime.now()
        #localizing time needed using pytz module
        utc=pytz.UTC
        now = utc.localize(now)

        if int(len(classes_all)) == 0:
            return 0
        else:
            for i in classes_all:
                if now > i:
                    classes_taken.append(i)
            return len(classes_taken)

    def get_number_classes_upcoming(self):
        classes_all = []
        for i in self.classes.all():
            classes_all.append(i.time)
        classes_upcoming = []
        now = datetime.datetime.now()
        #localizing time needed using pytz module
        utc=pytz.UTC
        now = utc.localize(now)

        if int(len(classes_all)) == 0:
            return 0
        else:
            for i in classes_all:
                if now < i:
                    classes_upcoming.append(i)
            return len(classes_upcoming)

    def get_number_studios(self):
        studios = []
        for i in self.classes.all():
            studios.append(i.studio.id)
        return len(studios)

    def get_number_credits(self):
        return int(self.credits)

    def add_credits(self, amount):
        credits_number = int(self.credits)
        new_credits_number = credits_number + int(amount)
        self.credits = new_credits_number
        return new_credits_number

    def spend_credits(self, amount):
        credits_number = int(self.credits)
        new_credits_number = credits_number - int(amount)
        self.credits = new_credits_number
        return new_credits_number



class Studio(models.Model):
    available_cities = [
        ("WA", "Warszawa"),
        ("KR", "Kraków"),
        ("LO", "Łódź"),
        ("GD", "Gdańsk)"),
        ("WR", "Wrocław"),
        ("PO", "Poznań"),
	]

    id              = models.AutoField(primary_key=True)
    studio_name	    = models.CharField(max_length=60, default="")
    owner_fr_name   = models.CharField(max_length=60, default="")
    owner_lt_name   = models.CharField(max_length=60, default="")
    password        = forms.CharField(widget=forms.PasswordInput)
    studio_type	    = models.CharField(max_length=60, default="")
    address 	    = models.CharField(max_length=120, default="")
    location        = models.CharField(max_length=24, default="21.01, 52.23")
    studio_city     = models.CharField(max_length=16, choices=available_cities, default="Warszawa")
    description     = models.TextField(default="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
    logo 		    = models.ImageField(
        upload_to='studio_profiles',
        height_field=None,
        width_field=None,
        default='sport/static/MockupPhoto01.png'
        )
    studio_photo    = models.ImageField(
        upload_to='studio_profiles',
        height_field=None,
        width_field=None,
        default='sport/static/MockupPhoto01.png'
        )
    trainers	    = models.ManyToManyField('sport.Trainer', related_name='studio_trainers', blank=True, default="")
    studio_classes  = models.ManyToManyField('sport.Class', related_name='studio_classes', blank=True, default="")
    studio_reviews	= models.ManyToManyField('sport.Review', related_name='studio_reviews', blank=True, default="")
    credits         = models.PositiveSmallIntegerField(default = 0)

    def __str__(self):
        return f"{self.studio_name}"

    '''
    def get_location(self):
        geolocator = Nominatim(user_agent="http")
        location = geolocator.geocode(self.address)
        return location.latitude, location.longitude
    '''

    def get_number_classes(self):
        classes = []
        for i in self.studio_classes.all():
            classes.append("class")
        return len(classes)

    def get_number_credits(self):
        return int(self.credits)

    def serialize(self):
        return {
            "id"            : self.id,
            "studio_name"   : self.studio_name,
            "owner_fr_name" : self.owner_fr_name,
            "owner_lt_name" : self.owner_lt_name,
            "password"      : self.password,
            "studio_type"   : self.studio_type,
            "address"       : self.address,
            "location"      : self.location,
            "city"          : self.studio_city,
            "description"   : self.description,
            "logo"          : self.logo.url,
            "studio_photo"  : self.studio_photo.url,
            "trainers"      : [trainer.id for trainer in self.trainers.all()],
            "classes"       : [this_class.id for this_class in self.studio_classes.all()],
            "reviews"       : [review.id for review in self.studio_reviews.all()],
            "credits"       : self.credits,
        }


class Studio_User(models.Model):
    user    = models.OneToOneField('sport.User', on_delete = models.CASCADE)
    studio  = models.OneToOneField('sport.Studio', on_delete = models.CASCADE)

class Class(models.Model):
    days_of_the_week = [
        ("MO", "Monday"),
        ("TU", "Tuesday"),
        ("WE", "Wednesday"),
        ("TH", "Thursday"),
        ("FR", "Friday"),
        ("SA", "Saturday"),
        ("SU", "Sunday"),
	]
    id 			= models.AutoField(primary_key=True)
    name 		= models.CharField(max_length=60)
    class_type  = models.CharField(max_length=60, default="")
    description = models.TextField(default="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
    studio 		= models.ForeignKey('sport.Studio', related_name='class_studio', on_delete=models.CASCADE)
    address 	= models.CharField(max_length=120)
    time        = models.DateTimeField(auto_now = False, default=datetime.datetime.now())
    date        = datetime.datetime.now().strftime("%d%m%Y")
    duration 	= models.PositiveSmallIntegerField()
    trainer 	= models.ForeignKey('sport.Trainer', related_name='class_trainer',on_delete=models.CASCADE)
    reviews 	= models.ManyToManyField('sport.Review', related_name='class_reviews', blank=True)
    price       = models.PositiveSmallIntegerField(default = 3)
    users       = models.ManyToManyField('sport.User', related_name='class_signed_up_users', blank=True)

sport/forms.py
from django import forms

class StudioForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = Studio

sport/templates/sport/aboutus.html
{% extends "sport/layout.html" %}


{% block body %}

<div class="full-image">
	{% load static %}
	<img src="{% static 'hero_about-us_desktop-ed.jpg' %}" class="full-image">
</div>

<div class="explanation2">
	<h1 class="big-title">About us</h1>
	<p class="bigger-p">FlexFit is revolutionizing the fitness and wellness industry
		by bringing together the world’s best classes and experiences into one app.
		Our mission? To motivate people to live inspired lives every day by introducing
		and seamlessly connecting them to soul-nurturing experiences.
		Whether you want to sweat it out with a HIIT class, unwind with a massage,
		or stream a yoga class from your home, we make it easy to prioritize your health and wellness.</p>


	<h2 style="margin-top: 100px;">Our core values</h2>
	<p class="bigger-p">At FlexFit and Mindbody, we understand that professional growth begins with personal growth.
		Our core values are expressed through everything we make, say and do.</p>

	<br>
	<br>
		<div class="icon-grid">
		<div>
			{% load static %}
			<img src="{% static '01. icon_impact-over-effort-01.svg' %}">
			<h5 style="margin-top:20px;">Impact Over Effort</h5>
		</div>
		<div>
			{% load static %}
			<img src="{% static '02. icon_bias-for-action-01.svg' %}">
			<h5 style="margin-top:20px;">Bias for Action</h5>
		</div>
		<div>
			{% load static %}
			<img src="{% static '03. icon-inclusion-01.svg' %}">
			<h5 style="margin-top:20px;">Inclusion is a Competitive Advantage</h5>
		</div>
		<div>
			{% load static %}
			<img src="{% static '04. icon_debate-decide-commit-01.svg' %}">
			<h5 style="margin-top:20px;">Debate, Decide, Commit</h5>
		</div>
		<div>
			{% load static %}
			<img src="{% static '05. icon_consciously-evolve-01.svg' %}">
			<h5 style="margin-top:20px;">Consciously Evolve</h5>
		</div>
		<div>
			{% load static %}
			<img src="{% static '06. icon_no-pain-01.svg' %}">
			<h5 style="margin-top:20px;">No Pain, No Gain</h5>
		</div>
		<div>
			{% load static %}
			<img src="{% static '07. icon_be-so-good-01.svg' %}">
			<h5 style="margin-top:20px;">Be So Good They Can’t Ignore You</h5>
		</div>
		<div>
			{% load static %}
			<img src="{% static '08. icon_work-hard-01.svg' %}">
			<h5 style="margin-top:20px;">Work Hard, Live Well</h5>
		</div>
	</div>
</div>
<div class="full-image">
	{% load static %}
	<img src="{% static 'collage_about-us_desktop_ed.png' %}" class="full-image">
</div>

<div class="explanation2">
	<h1 class="big-title">Inclusion is foundational</h1>
	<p class="bigger-p">We believe in creating opportunities for everyone,
		and that starts with empowering our team. We focus on something we all fundamentally need:
		a sense of belonging. With inclusion as our foundation, we create a space where everyone
		can thrive and make an impact</p>
</div>

<div class="explanation2">
	<h1 class="big-title">Want to join the team?</h1>
	<p class="bigger-p">Check out our open roles and apply — we’d love to hear from you.</p>
	<br>
	<br>
	<a class="try-button-big" href="{% url 'careers' %}" style="text-decoration:none;">Search open positions</a>
</div>


{% include 'sport/bottombar.html' %}
{% endblock %}

sport/templates/sport/careers.html
{% extends "sport/layout.html" %}

{% block body %}
<div class="full-image">
	{% load static %}
	<img src="{% static 'hero_careers_desktop-ed.jpg' %}" class="full-image">
</div>

<div class="explanation2">
	<h1 class="big-title">Life at FlexFit</h1>
	<p class="bigger-p">From New York to Montana to London and everywhere in between,
		you can find our growing team across the globe working passionately toward the same goal
		— making fitness and wellness accessible (and fun!) to everyone while simultaneously helping local businesses grow.</p>
	<br>
	<br>
	<h2 style="margin-top: 100px;">Our benefits</h2>
	<p class="bigger-p">FlexFit is now a part of Mindbody,
		a global leader in benefits that make working well and living well a priority. Visit the Mindbody page here to learn more.</p>
	<br>
	<br>
</div>
<div class="icon-grid" style="grid-template-columns: 1fr 1fr 1fr;">
	<div>
		{% load static %}
		<img src="{% static '09. icon_generous-paid-time-off-01.svg' %}">
		<h5 style="margin-top:20px;">Generous paid time off</h5>
	</div>
	<div>
		{% load static %}
		<img src="{% static '10. icon_family-leave-01.svg' %}">
		<h5 style="margin-top:20px;">Family leave & benefits</h5>
	</div>
	<div>
		{% load static %}
		<img src="{% static '11. icon_full-medical-01.svg' %}">
		<h5 style="margin-top:20px;">Full medical benefits</h5>
	</div>
	<div>
		{% load static %}
		<img src="{% static '12. icon_financial-wellbeing-01.svg' %}">
		<h5 style="margin-top:20px;">Financial wellbeing</h5>
	</div>
	<div>
		{% load static %}
		<img src="{% static '13. icon_work-from-anywhere-01.svg' %}">
		<h5 style="margin-top:20px;">Work from anywhere</h5>
	</div>
	<div>
		{% load static %}
		<img src="{% static '14. icon_wellness-body-mind-01.svg' %}">
		<h5 style="margin-top:20px;">Wellness for body & mind</h5>
	</div>
</div>

<div class="explanation2">
	<h1 class="big-title">Work happens everywhere</h1>
	<p class="bigger-p">For us, it’s not about showing up in an office every day, it’s about showing up at your best.
		We support our globally distributed workforce with virtual and in-person onboarding,
		cross-team meetings and software that makes it easy to stay connected, like Slack.</p>
	<br>
	<br>
</div>







{% include 'sport/bottombar.html' %}
{% endblock %}

sport/templates/sport/filenotfound.html
{% extends "sport/layout.html" %}

{% block body %}

<div style="display:flex; justify-content:center; align-items: center;">
	<br>
	<br>
	<br>
	<h1 class="big-title" style="margin: 50px;">Ooops, there has been a problem.</h1>
</div>
{% endblock %}

sport/templates/sport/partner-studio.html
{% extends "sport/layout-studio.html" %}

{% block body %}

<div class="explanation3" id="section1">
	<div style="width: 100%;">
		{% load static %}
		<img src="{% static 'CRO_Homepage_Hero_Desktop.jpg' %}" width="100%">
	</div>

	<div style="padding: 10px 50px; display: flex; flex-direction:column; align-items:center; justify-content:center;">
		<h3>Ready to start earning more?</h3>
		<p>List your venue on FitFlex, and earn money for every reservation booked.</p>
		<br>
		<br>
		<form action="{% url 'register_studio' %}" method="post">
			{% csrf_token %}
			<div class="partner-registration-form">
				<div>
					<label>Venue name</label>
					<input autofocus class="partner-form" type="text" name="venue_name">
				</div>
				<div>
					<label>City</label>
					<br>
					<select class="partner-form" id="studio_city" name="studio_city">
						<option value="Warszawa">Warszawa</option>
						<option value="Kraków">Kraków</option>
						<option value="Łódź">Łódź</option>
						<option value="Wrocław">Wrocław</option>
					</select>
				</div>
				<div>
					<label>First Name</label>
					<input class="partner-form" type="text" name="first_name">
				</div>
				<div>
					<label>Last Name</label>
					<input class="partner-form" type="text" name="last_name">
				</div>
				<div>
					<label>Business Type</label>
					<select class="partner-form" id="business_type" name="business_type">
						<option value="Warszawa">Yoga</option>
						<option value="Kraków">Pilates</option>
						<option value="Łódź">Crossfit</option>
						<option value="Wrocław">Gym</option>
						<option value="Wrocław">Others</option>
					</select>
				</div>
				<div>
					<label>Your e-mail</label>
					<input class="partner-form" type="email" name="email">
				</div>
				<div>
					<label>Password</label>
					<br>
					<input class="partner-form" type="password" name="password">
				</div>
				<div>
					<label>Confirmation</label>
					<br>
					<input class="partner-form" type="password" name="confirmation">
				</div>
				<div id="partner-regist-form-button-div">
					<input class="login-button" type="submit" value="Register">
				</div>

			</div>
		</form>
		<br>
		<p style="font-size:14px; margin-bottom: 10px;">Looking for user account?</p>
		<a class="standard_a" href="{% url 'login' %}">Log in here.</a>
		<br>
	</div>
</div>
<div class="explanation3" id="section2" style="padding: 100px; border-bottom: none;">
	<div>
		<h1>How it works?</h1>
		<br>
		<h3>Sign up online (in less than 10 minutes)</h3>
		<p>Tell us about your business and get a sense for how much you could make on the platform.</p>
		<br>
		<h3>Add your available classes and appointments</h3>
		<p>Tap into new audiences and reach thousands of ClassPass customers in your area. Leverage our Partner Portal to see how you’re performing.</p>
		<br>
		<h3>Get reservations, get paid</h3>
		<p>SmartSpot, our intelligent spot management tool, will look at your schedule and real time data to dynamically price your unfilled spots to maximize your revenue.</p>
		<br>
	</div>
	<div style="width: 100%;">
		{% load static %}
		<img src="{% static 'CRO_Homepage_HowItWorks.png' %}" width="100%">
	</div>
</div>

<div class="explanation3" id="section3" style="padding: 100px; border-bottom: none;">
	<div style="width: 100%;">
		{% load static %}
		<img src="{% static 'integration-photos3.png' %}" width="90%">
	</div>
	<div>
		<h1>Easily integrate your booking system</h1>
		<br>
		<h2>Our one-stop solution helps you manage, optimize and expand your business. We seamlessly integrate with over 25 booking systems worldwide.</h2>
		<br>
		<ul>
			<li>Easily sync your classes and availability into ClassPass</li>
			<li>Optimize your revenue generated with ClassPass' SmartTools</li>
			<li>Reduce the chance of overbooking</li>
		</ul>
	</div>
</div>

<div class="explanation2" id="section4">
	<div style="margin-bottom: 3rem;">
		<h1>Join a global network of top studios</h1>
		<br>
		<p>tudios of all sizes partner with ClassPass. Whether you’re an established studio or just starting out, you’ll be in good company.
		<br>- Andy Stenzler, Co-Founder, Rumble</p>
	</div>
	<div style="width: 100%;">
		{% load static %}
		<img src="{% static 'Desktop Partner Logos3.png' %}" width="70%">
	</div>
</div>
<div class="explanation2" id="section5">
	<div>
		<h1>Ready to get started?</h1>
		<br>
		<p>Grow your studio and livestream business by sharing your fitness and wellness experiences with ClassPass’ global audience.</p>
	</div>
	<br>
	<a class="try-button-big" href="#section1" style="text-decoration:none;">Get started today</a>

</div>
{% include 'sport/bottombar.html' %}
{% endblock %}

sport/templates/sport/profile.html
{% extends "sport/layout.html" %}


{% block body %}

    <!-- ----- ----- ----- EDIT PROFILE ----- ----- ----- -->

    <div class="main-box" id="edit-profile">
        <div class="half" style="border-top-right-radius: 0px; border-bottom-right-radius: 0px;">

        </div>
        <div class="half" style="border-top-left-radius: 0px; border-bottom-left-radius: 0px; padding: 30px;">
            <h3>Edit your profile information</h3>

        </div>

    </div>

    <!-- ----- ----- ----- PROFILE CALENDAR ----- ----- ----- -->

    <div class="main-box" id="profile-calendar">
        <div class="half" style="width: 80%; margin-right: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px;">
            <div class="profile-menu" >
                <div class="profile-menu-div">
                    <img src="{{user.profile_photo.url }}" class="profile-picture" alt="profile picture2">
                    <button class="edit-profile-button" onclick="makeEditProfileVisible()">
                        <i class="fa-solid fa-pen"></i>
                    </button>
                    <!--
                    <buton class="edit-profile-circle">
                        <i class="fa-solid fa-pen"></i>
                    </buton>
                    -->

                    <br>
                    <h4>{{user.first_name}} {{user.last_name}}</h4>
                    <h6>@{{user.username}}</h6>
                    <h5>
                        <i class="fa-solid fa-location-dot"></i>
                        {{user.get_city_display}}, PL
                    </h5>
                    <br>

                    <div style="width:100%; display:flex; flex-direction:row; justify-content:space-around;">
                        <div class="small-middle">
                            <h6>Classes taken</h6>
                            <h5>{{user.get_number_classes_taken}}</h5>
                        </div>
                        <div class="small-middle">
                            <h6>Studios visited</h6>
                            <h5>{{user.get_number_studios}}</h5>
                        </div>
                    </div>
                </div>
                <div class="profile-menu-div">
                    <div class="small-middle">
                        <a href="{% url 'index' %}">
                            <i class="fa-solid fa-calendar"></i>
                            <h5>Your classes</h5>
                        </a>
                    </div>
                    <div class="small-middle">
                        <a href="{% url 'index' %}" id="class-search-button" class="standard_a">
                            <i class="fa-solid fa-magnifying-glass"></i>
                            <h5>Find classes</h5>
                        </a>
                    </div>
                </div>
                <div class="profile-menu-div">
                    <a href="{% url 'credits' %}">How FlexFit works</a>
                </div>
            </div>

        </div>
        <div class="half" style="margin-right: 30px; border-top-left-radius: 0px; border-bottom-left-radius: 0px; padding: 30px; overflow-y: clip;">
            <div class="calendar-heading-div">
                <h3>Your classes</h3>
                <div style="display: flex; flex-direction: row; gap: 8px;">
                    <p>list</p>
                    <p>month</p>
                </div>
            </div>

            <div class="calendar" id="calendar" value="{{month_number}}">
                <div class="calendar-title">
                    <button class="small-button" id="previous-month-button">
                        <i class="fa-solid fa-caret-left"></i>
                    </button>
                    <h3 id="month-name" value="{{ month_name }}">{{ month_name }}</h3>
                    <h3 id="year-number" value="{{ year_number }}">{{ year_number }}</h3>
                    <button class="small-button" id="next-month-button">
                        <i class="fa-solid fa-caret-right"></i>
                    </button>
                </div>
                <div class="calendar-days">
                    <!-- days of the week -->
                    <div class="day-name"> Mon </div>
                    <div class="day-name"> Tue </div>
                    <div class="day-name"> Wed </div>
                    <div class="day-name"> Thu </div>
                    <div class="day-name"> Fri </div>
                    <div class="day-name"> Sat </div>
                    <div class="day-name"> Sun </div>
                    <!-- previous month days -->
                    {% for i in previous_days_list %}
                    <div class="day2"> {{i}} </div>
                    {% endfor %}
                    <!-- current month days -->
                    {% for i in days_in_month_list %}
                    {% if i == day_number %}
                    <div class="today" id="{{i}}">
                        <a href="{% url 'show_classes_for_day' %}" onclick="showClassesForTheDay({{i}})">
                        {{i}}
                        </a>
                    </div>
                    {% else %}
                    <div class="day" id="{{i}}">{{i}}</div>
                    {% endif %}
                    {% endfor %}
                    <!-- future month days -->
                    {% for i in future_days_list %}
                    <div class="day2">{{i}}</div>
                    {% endfor %}
                </div>
                <br>
                <!-- classes that day -->

            <div class="class-info-calendar" id="class-info-calendar">

            </div>


            </div>
        </div>

    </div>
    <!-- ----- ----- ----- END ----- ----- ----- -->

</div>



{% endblock %}

{% block script %}
{% load static %}
    <script src="{% static 'sport/sport.js' %}"></script>
{% endblock %}

sport/templates/sport/text.html
{% extends "sport/layout.html" %}

{% block body %}
<!-- ----- ----- ----- TEXT ----- ----- ----- -->
<div class="entry-text">
	{{ entry|safe }}
</div>

{% include 'sport/bottombar.html' %}

{% endblock %}